apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-{{.Chart.Name}}-{{.Chart.Version}}"
  labels:
spec:
  selector:
    matchLabels:
{{- include "labels" .| nindent 6 }}
  replicas: {{ .Values.deplyment.replicas | int }}
  template:
    metadata:
      labels:
{{- include "labels" .| nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.deplyment.image }}
        ports:
        - containerPort: {{ .Values.deplyment.exposed_pord | int }}