apiVersion: v1
kind: Service
metadata:
  name: service-{{.Release.Name}}-{{.Chart.Name}}
  labels:
{{include "labels" .| nindent 4}}
spec:
{{include "serviceType" .| nindent 2}}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP

  selector:
{{include "labels" .| nindent 4}}